/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthanticatedImport } from './routes/_authanticated'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const AuthanticatedIndexLazyImport = createFileRoute('/_authanticated/')()
const AuthanticatedProfileLazyImport = createFileRoute(
  '/_authanticated/profile',
)()
const AuthanticatedExpensesLazyImport = createFileRoute(
  '/_authanticated/expenses',
)()
const AuthanticatedCreateExpenseLazyImport = createFileRoute(
  '/_authanticated/create-expense',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AuthanticatedRoute = AuthanticatedImport.update({
  id: '/_authanticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthanticatedIndexLazyRoute = AuthanticatedIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AuthanticatedRoute,
} as any).lazy(() =>
  import('./routes/_authanticated/index.lazy').then((d) => d.Route),
)

const AuthanticatedProfileLazyRoute = AuthanticatedProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => AuthanticatedRoute,
} as any).lazy(() =>
  import('./routes/_authanticated/profile.lazy').then((d) => d.Route),
)

const AuthanticatedExpensesLazyRoute = AuthanticatedExpensesLazyImport.update({
  path: '/expenses',
  getParentRoute: () => AuthanticatedRoute,
} as any).lazy(() =>
  import('./routes/_authanticated/expenses.lazy').then((d) => d.Route),
)

const AuthanticatedCreateExpenseLazyRoute =
  AuthanticatedCreateExpenseLazyImport.update({
    path: '/create-expense',
    getParentRoute: () => AuthanticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authanticated/create-expense.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authanticated': {
      id: '/_authanticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthanticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authanticated/create-expense': {
      id: '/_authanticated/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof AuthanticatedCreateExpenseLazyImport
      parentRoute: typeof AuthanticatedImport
    }
    '/_authanticated/expenses': {
      id: '/_authanticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthanticatedExpensesLazyImport
      parentRoute: typeof AuthanticatedImport
    }
    '/_authanticated/profile': {
      id: '/_authanticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthanticatedProfileLazyImport
      parentRoute: typeof AuthanticatedImport
    }
    '/_authanticated/': {
      id: '/_authanticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthanticatedIndexLazyImport
      parentRoute: typeof AuthanticatedImport
    }
  }
}

// Create and export the route tree

interface AuthanticatedRouteChildren {
  AuthanticatedCreateExpenseLazyRoute: typeof AuthanticatedCreateExpenseLazyRoute
  AuthanticatedExpensesLazyRoute: typeof AuthanticatedExpensesLazyRoute
  AuthanticatedProfileLazyRoute: typeof AuthanticatedProfileLazyRoute
  AuthanticatedIndexLazyRoute: typeof AuthanticatedIndexLazyRoute
}

const AuthanticatedRouteChildren: AuthanticatedRouteChildren = {
  AuthanticatedCreateExpenseLazyRoute: AuthanticatedCreateExpenseLazyRoute,
  AuthanticatedExpensesLazyRoute: AuthanticatedExpensesLazyRoute,
  AuthanticatedProfileLazyRoute: AuthanticatedProfileLazyRoute,
  AuthanticatedIndexLazyRoute: AuthanticatedIndexLazyRoute,
}

const AuthanticatedRouteWithChildren = AuthanticatedRoute._addFileChildren(
  AuthanticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthanticatedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/create-expense': typeof AuthanticatedCreateExpenseLazyRoute
  '/expenses': typeof AuthanticatedExpensesLazyRoute
  '/profile': typeof AuthanticatedProfileLazyRoute
  '/': typeof AuthanticatedIndexLazyRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/create-expense': typeof AuthanticatedCreateExpenseLazyRoute
  '/expenses': typeof AuthanticatedExpensesLazyRoute
  '/profile': typeof AuthanticatedProfileLazyRoute
  '/': typeof AuthanticatedIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authanticated': typeof AuthanticatedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/_authanticated/create-expense': typeof AuthanticatedCreateExpenseLazyRoute
  '/_authanticated/expenses': typeof AuthanticatedExpensesLazyRoute
  '/_authanticated/profile': typeof AuthanticatedProfileLazyRoute
  '/_authanticated/': typeof AuthanticatedIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/create-expense' | '/expenses' | '/profile' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/create-expense' | '/expenses' | '/profile' | '/'
  id:
    | '__root__'
    | '/_authanticated'
    | '/about'
    | '/_authanticated/create-expense'
    | '/_authanticated/expenses'
    | '/_authanticated/profile'
    | '/_authanticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthanticatedRoute: typeof AuthanticatedRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthanticatedRoute: AuthanticatedRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authanticated",
        "/about"
      ]
    },
    "/_authanticated": {
      "filePath": "_authanticated.tsx",
      "children": [
        "/_authanticated/create-expense",
        "/_authanticated/expenses",
        "/_authanticated/profile",
        "/_authanticated/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_authanticated/create-expense": {
      "filePath": "_authanticated/create-expense.lazy.tsx",
      "parent": "/_authanticated"
    },
    "/_authanticated/expenses": {
      "filePath": "_authanticated/expenses.lazy.tsx",
      "parent": "/_authanticated"
    },
    "/_authanticated/profile": {
      "filePath": "_authanticated/profile.lazy.tsx",
      "parent": "/_authanticated"
    },
    "/_authanticated/": {
      "filePath": "_authanticated/index.lazy.tsx",
      "parent": "/_authanticated"
    }
  }
}
ROUTE_MANIFEST_END */
